In [1]:
import pandas as pd

In [4]:
data_latih = pd.read_csv('./tfidf/result_latih_tfidf.csv', encoding='utf-8')
data_latih

abdi  adaptasi     admin     aksen      akur      ala      alam  \
0   0.000000  0.053834  0.137409  0.137409  0.137409  0.00000  0.000000   
1   0.000000  0.151162  0.000000  0.000000  0.000000  0.00000  0.000000   
2   0.000000  0.118030  0.000000  0.000000  0.000000  0.00000  0.000000   
3   0.000000  0.151162  0.000000  0.000000  0.000000  0.00000  0.000000   
4   0.000000  0.000000  0.000000  0.000000  0.000000  0.12002  0.000000   
5   0.000000  0.118030  0.000000  0.000000  0.000000  0.00000  0.000000   
6   0.000000  0.151162  0.000000  0.000000  0.000000  0.00000  0.000000   
7   0.000000  0.118030  0.000000  0.000000  0.000000  0.00000  0.000000   
8   0.000000  0.118030  0.000000  0.000000  0.000000  0.00000  0.000000   
9   0.000000  0.118030  0.000000  0.000000  0.000000  0.00000  0.000000   
10  0.000000  0.151162  0.000000  0.000000  0.000000  0.00000  0.000000   
11  0.079246  0.000000  0.000000  0.000000  0.000000  0.00000  0.158492   
12  0.000000  0.118030  0.000000  0.000000  0.000000  0.00000  0.000000   

        alih  analytics  aplikasi  ...     ubah       udh      umur     usaha  \
0   0.000000   0.000000  0.274818  ...  0.00000  0.000000  0.000000  0.000000   
1   0.000000   0.000000  0.000000  ...  0.00000  0.000000  0.000000  0.000000   
2   0.159495   0.173151  0.000000  ...  0.00000  0.173151  0.000000  0.000000   
3   0.000000   0.000000  0.000000  ...  0.00000  0.000000  0.000000  0.000000   
4   0.000000   0.000000  0.000000  ...  0.12002  0.000000  0.000000  0.000000   
5   0.159495   0.173151  0.000000  ...  0.00000  0.173151  0.000000  0.000000   
6   0.000000   0.000000  0.000000  ...  0.00000  0.000000  0.000000  0.000000   
7   0.159495   0.173151  0.000000  ...  0.00000  0.173151  0.000000  0.000000   
8   0.159495   0.173151  0.000000  ...  0.00000  0.173151  0.000000  0.000000   
9   0.159495   0.173151  0.000000  ...  0.00000  0.173151  0.000000  0.000000   
10  0.000000   0.000000  0.000000  ...  0.00000  0.000000  0.000000  0.000000   
11  0.041954   0.000000  0.000000  ...  0.00000  0.000000  0.079246  0.237738   
12  0.159495   0.173151  0.000000  ...  0.00000  0.173151  0.000000  0.000000   

         via      win        ya        yg     zaman    label  
0   0.000000  0.00000  0.000000  0.000000  0.000000  POSITIF  
1   0.000000  0.00000  0.000000  0.000000  0.265824  NEGATIF  
2   0.000000  0.00000  0.173151  0.147450  0.000000  POSITIF  
3   0.000000  0.00000  0.000000  0.000000  0.265824  NEGATIF  
4   0.000000  0.12002  0.000000  0.352452  0.000000  NEGATIF  
5   0.000000  0.00000  0.173151  0.147450  0.000000  POSITIF  
6   0.000000  0.00000  0.000000  0.000000  0.265824  NEGATIF  
7   0.000000  0.00000  0.173151  0.147450  0.000000  POSITIF  
8   0.000000  0.00000  0.173151  0.147450  0.000000  POSITIF  
9   0.000000  0.00000  0.173151  0.147450  0.000000  POSITIF  
10  0.000000  0.00000  0.000000  0.000000  0.265824  NEGATIF  
11  0.079246  0.00000  0.000000  0.232715  0.000000  NEGATIF  
12  0.000000  0.00000  0.173151  0.147450  0.000000  POSITIF  

[13 rows x 184 columns]

In [5]:
data_uji = pd.read_csv('./tfidf/result_uji_tfidf.csv', encoding='utf-8')
data_uji

abdi  adaptasi  admin  aksen  akur  ala  alam      alih  analytics  \
0   0.0  0.000000    0.0    0.0   0.0  0.0   0.0  0.000000   0.000000   
1   0.0  0.237723    0.0    0.0   0.0  0.0   0.0  0.000000   0.000000   
2   0.0  0.118030    0.0    0.0   0.0  0.0   0.0  0.159495   0.173151   
3   0.0  0.151162    0.0    0.0   0.0  0.0   0.0  0.000000   0.000000   

   aplikasi  ...  ubah       udh      umur  usaha  via  win        ya  \
0       0.0  ...   0.0  0.000000  0.000000    0.0  0.0  0.0  0.000000   
1       0.0  ...   0.0  0.000000  0.303388    0.0  0.0  0.0  0.000000   
2       0.0  ...   0.0  0.173151  0.000000    0.0  0.0  0.0  0.173151   
3       0.0  ...   0.0  0.000000  0.000000    0.0  0.0  0.0  0.000000   

        yg     zaman    label  
0  0.23126  0.000000  NEGATIF  
1  0.00000  0.000000  POSITIF  
2  0.14745  0.000000  POSITIF  
3  0.00000  0.265824  NEGATIF  

[4 rows x 184 columns]

### Oversampling

In [6]:
print("Sebelum Oversampling, jumlah label 'POSITIF': {}".format(sum(data_latih['label'] == 'POSITIF')))
print("Sebelum Oversampling, jumlah label 'NEGATIF': {} ".format(sum(data_latih['label'] == 'NEGATIF')))

Sebelum Oversampling, jumlah label 'POSITIF': 7
Sebelum Oversampling, jumlah label 'NEGATIF': 6 


#### SMOTE

In [7]:
# SMOTE
# !pip install imblearn

from imblearn.over_sampling import SMOTE

In [15]:

X = data_latih.drop('label', axis=1)
y = data_latih['label']

sm = SMOTE(random_state=2)
X_res, y_res = sm.fit_resample(X, y)

In [16]:
print("Sebelum Oversampling, jumlah label 'POSITIF': {}".format(sum(y_res == 'POSITIF')))
print("Sebelum Oversampling, jumlah label 'NEGATIF': {} ".format(sum(y_res == 'NEGATIF')))

Sebelum Oversampling, jumlah label 'POSITIF': 7
Sebelum Oversampling, jumlah label 'NEGATIF': 7 


In [24]:
type(X_res)
type(y_res)

pandas.core.series.Series

In [25]:
print(X_res.shape)
print(y_res.shape)

(14, 183)
(14,)


### KNN Model

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
model = KNeighborsClassifier()

#### K-Fold Cross Validation

In [28]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.model_selection import KFold

In [ ]:
conf_matrices = []
class_reports = []

precisions = []
recalls = []
f1_scores = []

In [29]:
kFold = KFold(n_splits=10, random_state=42, shuffle=True)

for train_index, test_index in kFold.split(X_res):
    X_train, X_test = X_res.iloc[train_index], X_res.iloc[test_index]
    y_train, y_test = y_res.iloc[train_index], y_res.iloc[test_index]
    
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    precisions.append(precision_score(y_test, y_pred, average='macro'))
    recalls.append(recall_score(y_test, y_pred, average='macro'))
    f1_scores.append(f1_score(y_test, y_pred, average='macro'))
    
    conf_matrices.append(confusion_matrix(y_test, y_pred))
    class_reports.append(classification_report(y_test, y_pred))

for i, (conf_matrix, class_report) in enumerate(zip(conf_matrices, class_reports)):
    print(f"Fold {i+1}:\n")
    print("Confusion Matrix:\n", conf_matrix)
    print("\nClassification Report:\n", class_report)
    print("\n----------------------\n")

c:\Users\Dell 7300\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Dell 7300\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Dell 7300\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Dell 7300\anaconda3\lib\site-packages\sklearn\m

Fold 1:

Confusion Matrix:
 [[1 0]
 [1 0]]

Classification Report:
               precision    recall  f1-score   support

     NEGATIF       0.50      1.00      0.67         1
     POSITIF       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2


----------------------

Fold 2:

Confusion Matrix:
 [[1 0]
 [0 1]]

Classification Report:
               precision    recall  f1-score   support

     NEGATIF       1.00      1.00      1.00         1
     POSITIF       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2


----------------------

Fold 3:

Confusion Matrix:
 [[0 1]
 [0 1]]

Classification Report:
               precision    recall  f1-score   support

     NEGATIF       0.00      0.00    

In [30]:
import numpy as np

total_conf_matrix = np.zeros((2, 2))

for conf_matrix in conf_matrices:
    total_conf_matrix += conf_matrix

avg_conf_matrix = total_conf_matrix / len(conf_matrices)

print("Rata-Rata Confusion Matrix:\n", avg_conf_matrix)

Rata-Rata Confusion Matrix:
 [[0.8 0.7]
 [0.6 0.8]]


In [31]:
avg_precision = np.mean(precisions)
avg_recall = np.mean(recalls)
avg_f1_score = np.mean(f1_scores)

print("Rata-Rata Precision: ", avg_precision)
print("Rata-Rata Recall: ", avg_recall)
print("Rata-Rata F1-Score: ", avg_f1_score)

Rata-Rata Precision:  0.75
Rata-Rata Recall:  0.8
Rata-Rata F1-Score:  0.7666666666666666
